### ISSUE TITLE
Cannot compile anyway  :(

### ISSUE THREAD

**Issue by DBenS** [khalidsalomao/lz4-net#1]
Hi!

I´m trying to compile the package into VS2013 and I´m having a lot of errors related to different compilers and framework (I need it in .NET 4.0).

How can we solve this?

**Comment by khalidsalomao** [comment]
Can you post here the error message?

Thanks!
Em 2 de jan de 2016 5:33 PM, "David BS" notifications@github.com escreveu:

**Comment by DBenS** [comment]
Sure Kalid, mas dê-me poucos dias pois estou sem ele no momento - viagem de trabalho. Abração!
