### ISSUE TITLE
Destination buffer offset.

### ISSUE THREAD

**Issue by itapi** [khalidsalomao/lz4-net#3]
Hi!
I'm using this great wrapper in my project...and i need to compress data into another buffer (allocated already) but also with offset of the destination buffer... i mean i need the compressed data to be written in the dest buffer from the X position...

Compress() doesn't have any overload with destination offset....

What do you suggest me to do?

**Comment by khalidsalomao** [comment]
Hi @itapi , you could use the `LZ4_compress` method that `Compress` uses internally.
You could implement in your program a modified `Compress` implementation to allow destination offset. It is rather simple!

At [line 162](https://github.com/khalidsalomao/lz4-net/blob/master/LZ4net/Lz4.cs#L162) you could add the destination offset modifier:
```csahrp
            fixed (byte* pData = &data[offset], pBuffer = &buffer[8 + destOffset])
            {
                // compress data
                if (length > 0)
                {
                    compressedSize = (mode == Lz4Mode.Fast) ? 
                        LZ4_compress (pData, pBuffer, length) : 
                        LZ4_compressHC (pData, pBuffer, length);
                }
                // store original size and compressed size for latter decompression 
                ptr = (byte*)&(length);
                buffer[0 + destOffset] = ptr[0];
                buffer[1 + destOffset] = ptr[1];
                buffer[2 + destOffset] = ptr[2];
                buffer[3 + destOffset] = ptr[3];
                // compressed size
                ptr = (byte*)&(compressedSize);
                buffer[4 + destOffset] = ptr[0];
                buffer[5 + destOffset] = ptr[1];
                buffer[6 + destOffset] = ptr[2];
                buffer[7 + destOffset] = ptr[3];                
            }
```

**Comment by itapi** [comment]
@khalidsalomao  Actually I installed this library through the nuget package manager,but now i need to download the project from github and to change few lines to my needs(as you said above).

I've opened it via Visual studio 2017, 2 project of 5 didn't  even load ....

And these are the errors i get when trying to build...
![image](https://cloud.githubusercontent.com/assets/10478457/26498838/124e4334-4239-11e7-921c-71de45664f85.png)


Do you have any idea why I cant build the project?
Maybe I miss somthing?

Thanks in advance!

**Comment by khalidsalomao** [comment]
There is no need to build a new dll ;) ! You can just use the exported methods and create a class implementing your desired functionality.

Simply create a cs file with a class and the modified method using the `LZ4_compress` method.


About the screeshot:
It may not work in vs2017. The native c++ project seems to have had a problem loading...

**Comment by itapi** [comment]
@khalidsalomao  alright..I'll try man....In 2015 it may work?

**Comment by itapi** [comment]
@khalidsalomao  By the way...I want to include the lz4net.dll in my exe itself, I mean to embed the lz4 and load on runtime......but I've seen that there are also x86 and 64 directories in the same exe directory...and if i remove them and run the program it crashes...does the lz4net.dll choose on runtime on which dll to use?
And if so how could i include them too? They should be in the x86/x64 directories? I'm not sure if i can embed directory to the exe itself..



Another question,how do i get the compressed size of the data?(not the original size,the compressed!)

For example if i have big byte array,which stores inside few lz4 files,and lets say now wer'e in the 3rd file which begin to stored at `buffer[15666]`. I actually managed to compress and decompress again(thanks you your help! I really appreciate it),but i need also to get the compressed size....is it stored in the buffer somewhere?

Thanks in advance! Have a great day :)

**Comment by khalidsalomao** [comment]
Hi @itapi,

About the single exe, there are some utils that could help you with that. The dll is chosen at runtime!

You could also take a look into the project https://github.com/MiloszKrajewski/lz4net that implements a managed version of LZ4 that could make embedding easier for you!

The compressed size is stored in  bytes 4 to 7 of the buffer. see here https://github.com/khalidsalomao/lz4-net/blob/master/LZ4net/Lz4.cs#L178

Best!

**Comment by itapi** [comment]
@khalidsalomao  Hey!
Thank you so much for the response!
About the compressed size position, I managed to retrieve it from the buffer,thanks.

I would really like to hear about the utils you mentioned  above... I had also problems using  **MiloszKrajewski**'s project....I found your wrapper the best right now for my usage...
I know how to include and embed a dll, but the `lz4net` dll also load the x64 and x86 dlls from their directories...which I'm not sure how to embed to a single exe...understand?

I would be really thankful if you may help this time.

Thank you so much!
