### ISSUE TITLE
Use case for seekable stream

### ISSUE THREAD

**Issue by rraallvv** [khalidsalomao/lz4-net#5]
Since multiple files compression into a single file container is not supported by LZ4, I decided to merge/concatenate multiple files compressed separately, but now that I want to decompress only one file at a time I discovered that LZ4 streams are not seekable. My guess is that it shouldn't be difficult to implement since the only use case for a seekable LZ4 stream that one could thing of is the one I've described, so changing the current position would only require to "reset" the internal state.

Keep up the good work!

**Comment by nexrom88** [comment]
I started writing a wrapper stream for doing this. See:
[https://github.com/nexrom88/LZ4BlockCompression](https://github.com/nexrom88/LZ4BlockCompression)

**Comment by khalidsalomao** [comment]
Block compression was not in the scope of this wrapper. But nice to hear you are working on it 👍
