### ISSUE TITLE
.net6.0 support?

### ISSUE THREAD

**Issue by mdivatiamck** [khalidsalomao/lz4-net#6]
Is it possible to get the updated package with .net6.0 support so this can be used on linux?
we are compressing with lz4net so we can't decompress using any other nuget package.
We have tried to clone the repo and see if we could convert it but we are unable to compile the VC++ project since it seems to be missing lz4.h and lz4hc.h files in LZ4Dll project.
Thank you for your help.

**Comment by khalidsalomao** [comment]
Hi @mdivatiamck! 
Thanks for your interest in this library! I haven't actively updated it for a while, so I don't have immediate plans to release a new package with .NET 6.0 support.

However, I understand your need to use it on Linux with LZ4Net. Thankfully, compiling the LZ4 dependencies should be fairly straightforward. You can find the necessary code and header files in the official LZ4 repository:
[https://github.com/lz4/lz4/blob/dev/lib/lz4.h](https://github.com/lz4/lz4/blob/dev/lib/lz4.h)

If you encounter any difficulties during the compilation process, feel free to reach out and provide further details. I'm happy to help in any way I can.

Thanks for your understanding,
Khalid
